### ISSUE TITLE
Do I still need the nativescript-aws plugin? 

### ISSUE THREAD

**Issue by vbudilov** [EddyVerbruggen/nativescript-nodeify#1]
Do I still need the nativescript-aws plugin? 

From nativescript-nodeify's description looks like it automagically de-browserfies all of the libraries, but the instructions state that I need to install it nonetheless. Is that correct?

**Comment by EddyVerbruggen** [comment]
The example in the readme is correct. Perhaps later it's no longer required, but for now it is.

**Comment by vbudilov** [comment]
Got it.

**Comment by EddyVerbruggen** [comment]
With 0.5.0 I don't think you'll need nativescript-aws anymore.
