### ISSUE TITLE
Broken Dependency - nativescript-node.git#be2edd4

### ISSUE THREAD

**Issue by tedivm** [EddyVerbruggen/nativescript-nodeify#16]
I'm not sure if you rebased your copy of nativescript-node but the commit that you're referencing in this repository (be2edd4) does not exist, making it impossible to install this package via npm or tns install.

**Comment by tedivm** [comment]
```
$ make
yes "" | tns install
npm ERR! git rev-list -n1 be2edd4: fatal: ambiguous argument 'be2edd4': unknown revision or path not in the working tree.
```

**Comment by EddyVerbruggen** [comment]
Thanks @tedivm, sorry for the inconvenience. I indeed had to recreate the commit because of an incorrect git user. Will fix asap.

**Comment by EddyVerbruggen** [comment]
0.5.5 in on npm which fixes this nasty issue

**Comment by tedivm** [comment]
Thanks for the quick fix!
