### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by davidxiao** [EddyVerbruggen/nativescript-nodeify#2]
Hi,
   got the below error on Mac, although it seems downloaded into node_moduels.

192-168-1-108:test01 davidxiao$ tns --version
2.4.2

tried for js version and angular version, having the same issue.

192-168-1-108:test01 davidxiao$ tns plugin add nativescript-nodeify
npm ERR! addLocal Could not install /Users/davidxiao/works/mobile/ns/test01/nativescript-nodeify@latest/nativescript-node
ENOENT: no such file or directory, open '/Users/davidxiao/works/mobile/ns/test01/nativescript-nodeify@latest/nativescript-node'
# plugin add
┌─────────┬───────────────────────────┐
│ Usage   │ Synopsis                  │
│ General │ $ tns plugin add <Plugin> │
└─────────┴───────────────────────────┘

Installs the specified plugin and any packages that it depends on.

### Attributes

    * <Plugin> is a valid NativeScript plugin, specified by any of the following.
       * A <Name> or <Name>@<Version> where <Name> is the name of a plugin that is published in the npm registry and <Version> is a valid version of this plugin.
       * A <Local Path> to the directory which contains the plugin, including its package.json file.
       * A <Local Path> to a .tar.gz archive containing a directory with the plugin and its package.json file.
       * A <URL> which resolves to a .tar.gz archive containing a directory with the plugin and its package.json file.
       * A <git Remote URL> which resolves to a .tar.gz archive containing a directory with the plugin and its package.json file

**Comment by EddyVerbruggen** [comment]
Sorry for that, 0.3.0 should be better.

**Comment by davidxiao** [comment]
thanks you :)
