### ISSUE TITLE
ReferenceError:Buffer is not defined & Frame: function:'require',file 

### ISSUE THREAD

**Issue by kumarandena** [EddyVerbruggen/nativescript-nodeify#22]
I tried to use sqlite-cipher plugin with my nativescript angular app. But that time i got issue, please refer below screenshot.
![screenshot_2017-08-10-15-18-00 1](https://user-images.githubusercontent.com/30895291/29169161-3590f952-7df0-11e7-95ed-37c57d37229c.png)

After that i have searched and followed the nativescript-nodeify plugin.
"https://www.nativescript.org/blog/how-to-use-any-npm-module-with-nativescript"

After implemented the nativescript-nodeify, then tried to build and run the project. But i got again errors like,
![screenshot_2017-08-10-16-36-14 1](https://user-images.githubusercontent.com/30895291/29169270-d360a768-7df0-11e7-91c6-15ffcbd0fe62.png)

How to resolve this issue. 

Thanks.

**Comment by kumaran-dena** [comment]
Here i have attached my app's log file.

[nodeify_logcat.txt](https://github.com/EddyVerbruggen/nativescript-nodeify/files/1214791/nodeify_logcat.txt)

**Comment by soflass1293** [comment]
5f

**Comment by tigrenok00** [comment]
Happens to me as well , @EddyVerbruggen, could you help please?

**Comment by metaphalon** [comment]
I encountered the same issue.
It seems that something has changed in the npm module loading.
When I manually add 
`var Buffer = require("buffer").Buffer;`
at the start of the make.hash.js File in the node_modules directory, this error disappears.

This is no solution but perhaps a hint how this issue can be resolved.
I'm a nativescript noob, so I have no idea, where to start. :-(

**Comment by EddyVerbruggen** [comment]
Before diving into this I have to ask: did you guys include `require("nativescript-nodeify");` before running the problematic code runs? For instance @kumaran-dena's `make-hash.js` on line 3 seems to try and load `Buffer` which should be patched in case that aforementioned require is added.

**Comment by metaphalon** [comment]
This solves it for me, thanks.
I assumed that this would be pulled in when using a shimed module.
