### ISSUE TITLE
TS2304: Cannot find name 'Buffer'.

### ISSUE THREAD

**Issue by bonfi7** [EddyVerbruggen/nativescript-nodeify#23]
Hi,
I get this error also using nativescript-nodeify instead of deprecated nativescript-aws.
I had follow suuggested steps:
$ npm install amazon-cognito-identity-js --save
$ tns plugin add nativescript-nodeify

and in my package.json added lines for correct parsing.

I had also remove the platform and the node_modules folder before build.
I really don't know how can get it works...

Her my configuration files (renamed to txt...)
[package.json.txt](https://github.com/EddyVerbruggen/nativescript-nodeify/files/1308226/package.json.txt)
[tsconfig.aot.json.txt](https://github.com/EddyVerbruggen/nativescript-nodeify/files/1308227/tsconfig.aot.json.txt)
[tsconfig.json.txt](https://github.com/EddyVerbruggen/nativescript-nodeify/files/1308228/tsconfig.json.txt)
[tslint.json.txt](https://github.com/EddyVerbruggen/nativescript-nodeify/files/1308229/tslint.json.txt)
[webpack.config.js.txt](https://github.com/EddyVerbruggen/nativescript-nodeify/files/1308230/webpack.config.js.txt)

.

Thanks

**Comment by ethanharlig** [comment]
Any fix for this? I am having the same issue.

**Comment by bonfi7** [comment]
Hi @ethanharlig,
yep, I get it work! The magic is in the package.json where I had to include manually "buffer": "5.0.2", and other dependencies of nodeify. Here my files.
[package.txt](https://github.com/EddyVerbruggen/nativescript-nodeify/files/1374576/package.txt)
[tsconfig.aot.txt](https://github.com/EddyVerbruggen/nativescript-nodeify/files/1374577/tsconfig.aot.txt)
[tsconfig.txt](https://github.com/EddyVerbruggen/nativescript-nodeify/files/1374578/tsconfig.txt)
[tslint.txt](https://github.com/EddyVerbruggen/nativescript-nodeify/files/1374579/tslint.txt)

**Comment by collindutter** [comment]
@EddyVerbruggen are these really the required steps for getting aws-sdk to work? If so, shouldn't they be in the AWS section of the README?
