### ISSUE TITLE
Build error: 'Cannot find module 'file-system/file-system-access'' when using together with 'nativescript/xml2js'

### ISSUE THREAD

**Issue by lusocoding** [EddyVerbruggen/nativescript-nodeify#24]
**Steps to reproduce**

Run the following commands which will create a blank NativeScript/Angular app:
```
tns create ns-tests-app --template tns-template-blank-ng
cd ns-tests-app
tns plugin add nativescript-nodeify
tns platform add android
npm install --save nativescript-xml2js
tns build android
```

Edit the app/home.component.ts file:
```javascript
import { Component, OnInit } from "@angular/core";
import * as xml from 'nativescript-xml2js';

@Component({
    selector: "Home",
    moduleId: module.id,
    templateUrl: "./home.component.html"
})
export class HomeComponent implements OnInit {
    constructor() {
        xml.parseString('<?xml version="1.0"?><Books><Book title="Lorem ipsum"></Book></Books>',
            (err, result) => {
                if (err) {
                    console.log(err.message);
                } else {
                    console.log(result);
                }
            });
    }
    ngOnInit(): void {
    }
}
```

Build android app
```
tns build android
```

**Workaround to be able to run the app**

Sometimes I'm able to run the app with both modules installed if I remove the android platform and the node_modules folder, perform a tns install and add the android platform again, such as below:

```
tns platform remove android
rmdir node_modules
tns install 
tns platform add android
tns build android
```

**Comment by soflass1293** [comment]
Hello
I cannot find the way to make a project running properly with Amazon Cognito and AWS SDK using both 'aws-sdk', 'nativescript-sdk' or 'amazon-cognito-identity-js'.
I tried your method but it didn't work properly!
Please if it worked for you can you provide a TypeScript project including AWS Cognito and Amazon SDK, I will apperciate this a lot.
Thank you very much!
