### ISSUE TITLE
error in command line: tns plugin add nativescript-nodeify

### ISSUE THREAD

**Issue by cmargulhano** [EddyVerbruggen/nativescript-nodeify#28]
$ tns plugin add nativescript-nodeify
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "util/util.js": name can only contain URL-friendly characters

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/claudio/.npm/_logs/2017-10-09T17_34_34_808Z-debug.log
Command npm install nativescript-nodeify --save failed with exit code 1
# plugin add

┌─────────┬───────────────────────────┐
│ Usage   │ Synopsis                  │
│ General │ $ tns plugin add <Plugin> │
└─────────┴───────────────────────────┘

Installs the specified plugin and any packages that it depends on.

### Attributes

    * <Plugin> is a valid NativeScript plugin, specified by any of the following.
        * A <Name> or <Name>@<Version> where <Name> is the name of a plugin that is published in the npm registry and <Version> is a valid version of this plugin.
        * A <Local Path> to the directory which contains the plugin, including its package.json file.
        * A <Local Path> to a .tar.gz archive containing a directory with the plugin and its package.json file.
        * A <URL> which resolves to a .tar.gz archive containing a directory with the plugin and its package.json file.
        * A <git Remote URL> which resolves to a .tar.gz archive containing a directory with the plugin and its package.json file.

**Comment by ukch** [comment]
I was having this issue. I believe it's related to #29.
