### ISSUE TITLE
This plugin breaks build tools

### ISSUE THREAD

**Issue by ukch** [EddyVerbruggen/nativescript-nodeify#29]
Because of the way this plugin works (rewriting almost the whole of `node_modules`), this breaks all non-blacklisted build tools (ie. Babel) and creates a huge headache to debug and use.

Instead of the current approach (rewrite everything in `node_modules` except those modules that are blacklisted), I propose the following approach:

1. Read the project's `package.json` and note the `dependencies` (`devDependencies` are ignored)
2. For each noted module:
   * Rewrite imports for the module
   * Repeat step 1, but this time for the module's own `package.json`.

In the meanwhile, I have made a fork of this project for my own use, that uses a whitelist instead of a blacklist. If anyone might find it helpful, it is available at [ukch/nativescript-nodeify](https://github.com/ukch/nativescript-nodeify) (any user will probably need to modify the whitelist for their own needs)

**Comment by westlakem** [comment]
Any updates on doing this? I feel it would also reduce the build time drastically.

**Comment by westlakem** [comment]
To add to this, every time I want to add a new dependency (after this plugin does its work) I have to nuke the node modules directory and do a full `npm install`.

**Comment by CharlesJu1** [comment]
I also have to remove the node modules directory and do a full npm install if I remove a platform and add back the platform again. Can this plugin leave the files in node modules untouched and rather make changes to the files in "build" directory?

**Comment by EddyVerbruggen** [comment]
@CharlesJu1 That would be nice. If anyone is up for it please go ahead.

**Comment by CharlesJu1** [comment]
@EddyVerbruggen Since this plugin already rewrites the node modules, why it is still needed to require nativescript-nodeify as in the following:

```
require('nativescript-nodeify');
var AmazonCognitoIdentity  = require('amazon-cognito-identity-js');
```

**Comment by EddyVerbruggen** [comment]
@CharlesJu1 Because then this will run: https://github.com/EddyVerbruggen/nativescript-nodeify/blob/master/nodeify.js

**Comment by CharlesJu1** [comment]
@EddyVerbruggen I gave it a try to make the plugin patch the node_modules in the platforms folder rather than the source folder. It seems working ok. Here is what I did:
1. In package.json, change the before_prepare hook to after_prepare hook and points to a new script file called patch_platform.js
2. In patch_platform.js, require the platform specific patch-npm-packages.js.
3. In patch-npm-packages.js, on line 227, require the package.json file from the source dir. The code logic is the same as before.

I have submitted a pull request. Could you review the changes?

**Comment by EddyVerbruggen** [comment]
Published with 0.6.0, thank you, @CharlesJu1!

If anyone using Webpack running into issues with 0.6.0 that they didn't have when using an older version: please leave a comment.

**Comment by kaurag007ph** [comment]
I'm using version 0.7.0 of this plugin. It works with regular `tns run ios` but an error occurs every time I run it with `--bundle`.

It says `Cannot find module `myfilepath/app/tns_modules/nativescript-nodeify/patch-npm-packages.js`

**Comment by EddyVerbruggen** [comment]
@kaurag007ph yeah that's what I figured (my previous comment). Thanks for confirming that.

**Comment by EddyVerbruggen** [comment]
Not yet, but I'm trying to figure something out.

**Comment by kaurag007ph** [comment]
can we reopen the issue for now?

**Comment by EddyVerbruggen** [comment]
I'll open a new one, specifically for bundling.

**Comment by amolpwani** [comment]
Hi @EddyVerbruggen, do you have any update for this bundling issue.
It says Cannot find module myfilepath/app/tns_modules/nativescript-nodeify/patch-npm-packages.js`
Your response will be really helpful

**Comment by stulli103** [comment]
I am unfortunately also experiencing the same problem as @amolpwani right now.

**Comment by ak5** [comment]
+1 for reopening

**Comment by Falu-G** [comment]
Hi @EddyVerbruggen, do you have any update for this bundling issue.
I am unfortunately also experiencing the same problem as  @amolpwani right now.
Your response will be really helpful
