### ISSUE TITLE
Getting "Cannot find module 'file-system/file-system-access'"

### ISSUE THREAD

**Issue by vbudilov** [EddyVerbruggen/nativescript-nodeify#3]
Hi, 

Any idea what might be causing this? 

Thanks,
Vladimir

```
Executing before-prepare hook from /home/vova/dev/ideas/eiq/eiq-ns/hooks/before-prepare/nativescript-nodeify.js
module.js:472
    throw err;
    ^

Error: Cannot find module 'file-system/file-system-access'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/vova/dev/ideas/eiq/eiq-ns/node_modules/nativescript-nodeify/node_modules/nativescript-node/fs.js:8:24)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by EddyVerbruggen** [comment]
What have you done that leaded up to this error exactly?

**Comment by vbudilov** [comment]
I ran `tns build android`

```
vova@odessa:~/dev/xxxx/eeee/eeee-ns$ tns build android
Executing before-prepare hook from /home/vova/dev/ideas/eiq/eiq-ns/hooks/before-prepare/nativescript-dev-android-snapshot.js
Executing before-prepare hook from /home/vova/dev/ideas/eiq/eiq-ns/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 2.0.10
Executing before-prepare hook from /home/vova/dev/ideas/eiq/eiq-ns/hooks/before-prepare/nativescript-nodeify.js
module.js:472
    throw err;
    ^

Error: Cannot find module 'file-system/file-system-access'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/vova/dev/ideas/eiq/eiq-ns/node_modules/nativescript-nodeify/node_modules/nativescript-node/fs.js:8:24)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by EddyVerbruggen** [comment]
I just did this without problem, can you try that with the latest version? Also, could be some other plugin messing it up, so can you post your `package.json`?

```
tns create nodeifytest
cd nodeifytest
tns platform add ios; tns platform add android
tns plugin add nativescript-nodeify
tns build android
```

**Comment by vbudilov** [comment]
I'll have to test again, maybe from scratch. I'm also using the `nativescript-aws` plugin, so don't know if that makes a difference.

**Comment by EddyVerbruggen** [comment]
Yeah, I didn't design those two to cooperate as you can just use nativescript-nodeify with Cognito which already includes AWS.

Did you see the [Cognito example](https://github.com/EddyVerbruggen/nativescript-nodeify#amazon-cognito-identity-js-with-aws-sdk)?

**Comment by vbudilov** [comment]
Ok, let me try without it. I guest this is no longer the case :) https://github.com/EddyVerbruggen/nativescript-nodeify/issues/1

**Comment by EddyVerbruggen** [comment]
Please update to 0.5.0. It takes a different approach which should take care of this issue.

**Comment by tedivm** [comment]
I'm still having this exact same issue with version 0.5.3.

**Comment by kwong93** [comment]
I have this issue when adding the plugin to an existing project, however I ran:

```
tns create nodeifytest
cd nodeifytest
tns platform add ios; tns platform add android
tns plugin add nativescript-nodeify
tns build android
```

and that worked.

**Comment by tedivm** [comment]
Update- I can fix this issue by erasing both the ios platform directory *and* the node_modules directory and doing a reinstall.

**Comment by simplicii** [comment]
issue still there. I need to delete the node_modules folder very often.

**Comment by zahid-dapperapps** [comment]
Why is this closed? Issue is still present in 0.5.5

**Comment by westlakem** [comment]
Still an issue 8 months later

**Comment by EddyVerbruggen** [comment]
Feel free to contribute guys. This is VERY hard to get right.

Also, I'm interested to learn if by now there are better ways to use node packages in a NativeScript runtime. There have been some initiatives I haven't had the time to explore, unfortunately.

**Comment by westlakem** [comment]
@EddyVerbruggen I think your approach with the AWS SDK stuff was right... there's just too much to randomly change
