### ISSUE TITLE
Cannot find module 'nativescript-nodeify/node_modules/nativescript-node/fs'

### ISSUE THREAD

**Issue by asultonov** [EddyVerbruggen/nativescript-nodeify#4]
I can't use the module, because receive the following error:
> Executing before-prepare hook from /Users/mini/Projects/sayhun-native/hooks/before-prepare/nativescript-nodeify.js
> module.js:472
>     throw err;
>     ^
> 
> Error: Cannot find module 'nativescript-nodeify/node_modules/nativescript-node/fs'
>     at Function.Module._resolveFilename (module.js:470:15)
>     at Function.Module._load (module.js:418:25)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/Users/mini/Projects/sayhun-native/node_modules/nativescript-nodeify/patch-npm-packages.js:16:10)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)

I note that in the directory nativescript-nodeify/node_modules there are only 2 folders: punycode and url.

**Comment by EddyVerbruggen** [comment]
Please update to 0.5.0. It takes a different approach which should take care of this issue.

If you still experience it, please let me know what the library is you're trying to fix with this plugin.

**Comment by enissay14** [comment]
Still having the same problem with 0.5.3 version. I am trying to use the plugin with Buffer.

**Comment by efgonz** [comment]
I have the same issue with v0.5.5
