### ISSUE TITLE
Module not working package with crypto

### ISSUE THREAD

**Issue by KoenPaas** [EddyVerbruggen/nativescript-nodeify#55]
I try to use ripple-lib package but get the same error: crypto.randomBytes(16) is not a function.
This is on nativescript, vuejs, iOS. Is there any other way to make ripple-lib NPM package work with nativescript?

**Comment by bonustrack** [comment]
+1

**Comment by acidbiscuit** [comment]
Please, check my findings about using `ripple-lib` with NativeScript on [stackoverflow](https://stackoverflow.com/questions/53172766/how-to-use-ripple-lib-with-nativescript/53925032#53925032). I won't duplicate the answer here, as eventually solution does not use `nativescript-nodeify` library. 

Hopefully, it helps.

**Comment by bonustrack** [comment]
Interesting, thank you for this feedback @acidbiscuit
