### ISSUE TITLE
Error when running in iOS

### ISSUE THREAD

**Issue by jayandh06** [EddyVerbruggen/nativescript-nodeify#6]
I get following error when running the command

> **tns run ios**

Executing before-watch hook from /Users/jayandhanrajasundaram/Documents/Nativescript/BlueCare/hooks/before-watch/nativescript-dev-typescript.js
Found peer TypeScript 2.1.6
module.js:472
    throw err;
    ^

**Error: Cannot find module 'nativescript-randombytes'**
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> **(/Users/jayandhanrajasundaram/Documents/Nativescript/BlueCare/node_modules/nativescript-nodeify/node_modules/crypto-browserify/index.js:3:80)**
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

TypeScript compiler failed with exit code 1
Sending exception report (press Ctrl+C to stop).....

package.json
--------------
```js
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.BlueCare",
    "nodeify": {
      "package-dependencies": {
        "aws-sdk": [
          {
            "xml/browser_parser": "xml/node_parser"
          }
        ]
      }
    },
    "tns-ios": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "@angular/common": "2.4.3",
    "@angular/compiler": "2.4.3",
    "@angular/core": "2.4.3",
    "@angular/forms": "2.4.3",
    "@angular/http": "2.4.3",
    "@angular/platform-browser": "2.4.3",
    "@angular/platform-browser-dynamic": "2.4.3",
    "@angular/router": "3.4.3",
    "aws-sdk": "^2.22.0",
    "nativescript-angular": "1.4.0",
    "nativescript-nodeify": "^0.5.1",
    "nativescript-oauth": "1.3.0",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.0.1",
    "tns-core-modules": "2.5.0"
  },
  "devDependencies": {
    "babel-traverse": "6.23.1",
    "babel-types": "6.23.0",
    "babylon": "6.16.1",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "^0.3.5",
    "typescript": "~2.1.0",
    "zone.js": "~0.7.2"
  }
}
```

**Comment by EddyVerbruggen** [comment]
Found the problem: this plugin's hook script is altering the typescript package. Let's exclude that.

**Comment by EddyVerbruggen** [comment]
Please update to 0.5.2 and try again.
