### ISSUE TITLE
Demo app relaunch issue

### ISSUE THREAD

**Issue by jayandh06** [EddyVerbruggen/nativescript-nodeify#7]
I get the below issue when i run following command

**npm run demo.ios**

Scenario
-----------
Above command runs successfully and launches the app the first time, when i try to run same command second time i get the below error

**Note:**
-----------

In order to avoid the below error i have to delete the following folders
1) hooks 
2) node_modules 
3) platforms 

and run above command as if its first time running the application.

Error message
----------------
$ npm run demo.ios

> nativescript-nodeify@0.5.1 demo.ios /Users/jayandhanrajasundaram/Documents/workspace/nativescript-nodeify
> npm run preparedemo && cd demo && tns debug ios

> nativescript-nodeify@0.5.1 preparedemo /Users/jayandhanrajasundaram/Documents/workspace/nativescript-nodeify
> cd demo && tns plugin add .. && tns install 

npm ERR! addLocal Could not install /Users/jayandhanrajasundaram/Documents/workspace/nativescript-nodeify/demo/node_modules/readable-stream/string_decoder/@*
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "install" ".." "--save"
npm ERR! node v7.5.0
npm ERR! npm  v4.3.0
npm ERR! path /Users/jayandhanrajasundaram/Documents/workspace/nativescript-nodeify/demo/node_modules/readable-stream/string_decoder/@*
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/jayandhanrajasundaram/Documents/workspace/nativescript-nodeify/demo/node_modules/readable-stream/string_decoder/@*'
npm ERR! enoent ENOENT: no such file or directory, open '/Users/jayandhanrajasundaram/Documents/workspace/nativescript-nodeify/demo/node_modules/readable-stream/string_decoder/@*'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jayandhanrajasundaram/.npm/_logs/2017-03-06T17_27_45_048Z-debug.log
Command npm failed with exit code 254
# plugin add

┌─────────┬───────────────────────────┐
│ Usage   │ Synopsis                  │
│ General │ $ tns plugin add <Plugin> │
└─────────┴───────────────────────────┘

Installs the specified plugin and any packages that it depends on.

### Attributes

    * <Plugin> is a valid NativeScript plugin, specified by any of the following.
        * A <Name> or <Name>@<Version> where <Name> is the name of a plugin that is published in the npm registry and <Version> is a valid version of this plugin.
        * A <Local Path> to the directory which contains the plugin, including its package.json file.
        * A <Local Path> to a .tar.gz archive containing a directory with the plugin and its package.json file.
        * A <URL> which resolves to a .tar.gz archive containing a directory with the plugin and its package.json file.
        * A <git Remote URL> which resolves to a .tar.gz archive containing a directory with the plugin and its package.json file.

Sending exception report (press Ctrl+C to stop).....

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "run" "preparedemo"
npm ERR! node v7.5.0
npm ERR! npm  v4.3.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! nativescript-nodeify@0.5.1 preparedemo: `cd demo && tns plugin add .. && tns install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the nativescript-nodeify@0.5.1 preparedemo script 'cd demo && tns plugin add .. && tns install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nativescript-nodeify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd demo && tns plugin add .. && tns install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nativescript-nodeify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nativescript-nodeify
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jayandhanrajasundaram/.npm/_logs/2017-03-06T15_38_02_150Z-debug.log

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "run" "demo.ios"
npm ERR! node v7.5.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nativescript-nodeify@0.5.1 demo.ios: `npm run preparedemo && cd demo && tns debug ios`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nativescript-nodeify@0.5.1 demo.ios script 'npm run preparedemo && cd demo && tns debug ios'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nativescript-nodeify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run preparedemo && cd demo && tns debug ios
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nativescript-nodeify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nativescript-nodeify
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jayandhanrajasundaram/.npm/_logs/2017-03-06T15_38_02_189Z-debug.log

**Comment by EddyVerbruggen** [comment]
Please use a fresh project to retest if you want.
