### ISSUE TITLE
Unable to sync changes to Demo / regular app

### ISSUE THREAD

**Issue by jayandh06** [EddyVerbruggen/nativescript-nodeify#8]
**Scenario:**
----------

I get the below error whenever i make changes to js file, in my case i made changes to (main-view-model.js) in DEMO app, just changing AWS Userpool or S3 related ids and auth info. related to my AWS account.

**Error message:**
---------------
Unable to sync files. Error is: 
9:54:54 AM - Compilation complete. Watching for file changes.

Executing before-prepare hook from /Users/jayandhanrajasundaram/Documents/Nativescript/BlueCare/hooks/before-prepare/nativescript-dev-android-snapshot.js
Executing before-prepare hook from /Users/jayandhanrajasundaram/Documents/Nativescript/BlueCare/hooks/before-prepare/nativescript-dev-typescript.js
Executing before-prepare hook from /Users/jayandhanrajasundaram/Documents/Nativescript/BlueCare/hooks/before-prepare/nativescript-nodeify.js
module.js:472
    throw err;
    ^

Error: Cannot find module 'file-system/file-system-access'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jayandhanrajasundaram/Documents/Nativescript/BlueCare/node_modules/nativescript-node/fs.js:8:24)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by EddyVerbruggen** [comment]
Can you share a way for me to reproduce the problem please? A few steps I can throw into my console preferably.

**Comment by jayandh06** [comment]
When Demo app is running, just make some valid change to 'main-view-model.js' file, file change sync kicks in and i get the error immediately.

The same error happens when i make change to my nativescript app that uses nativescript-nodeify and typescript plugin.

**Comment by EddyVerbruggen** [comment]
I'll look at that first issue, but for the second: did you already update to 0.5.2?

**Comment by jayandh06** [comment]
Yes, i did get the latest 0.5.2

**Comment by EddyVerbruggen** [comment]
I think you uncovered a problem with livesync. Before {N} 2.5.0 livesync was not enabled by default so I didn't notice it.

The plugin now detects when running with livesync and skips the hook. That solves it for my fresh(!) project.
